//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoApplication.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Customer
    {
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
        public string Contact { get; set; }
        public Nullable<long> Turnover { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<int> CityID { get; set; }
    
        public virtual TBL_City TBL_City { get; set; }
    }
}
